# Generated by Django 2.2.1 on 2019-06-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
